// One bill, two M-Pesa transactions on the till: "+ another M-Pesa payment"
// adds an amount and a code; the invoice carries two M-Pesa rows with both codes.
//   BASE=http://pos.localhost:8080 node mpesa_split_probe.mjs   (test site: bills a real invoice)
import { chromium } from 'playwright';
const BASE = process.env.BASE || 'http://pos.localhost:8080', TABLE = process.env.TABLE || 'Table 10';
const GUEST = 'Split ' + Date.now().toString().slice(-4);
const C1 = 'Q' + Date.now().toString(36).toUpperCase().slice(-9).padStart(9, 'A'), C2 = 'R' + Date.now().toString(36).toUpperCase().slice(-9).padStart(9, 'B');
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1500, height: 900 } })).newPage();
const report = []; const ok = (n, pass, d = '') => { report.push(pass); console.log(`${pass ? 'PASS' : 'FAIL'}  ${n}${d ? '  — ' + String(d).slice(0, 220) : ''}`); };
const errs = []; p.on('pageerror', e => errs.push(String(e).slice(0, 120)));
await p.goto(`${BASE}/login`, { waitUntil: 'domcontentloaded' });
await p.fill('#login_email', 'cashier@etham.co.ke'); await p.fill('#login_password', 'Cashier@2026'); await p.click('button.btn-login');
await p.waitForURL(/\/app|\/desk/, { timeout: 60000 }).catch(() => {});
await p.goto(`${BASE}/app/restaurant-manage`, { waitUntil: 'domcontentloaded' }); await p.waitForTimeout(15000);
await p.getByText('R 2', { exact: true }).first().click().catch(() => {}); await p.waitForTimeout(3000);
await p.evaluate(() => localStorage.removeItem('rm_waiter_session'));
await p.getByRole('button', { name: 'Seat guest' }).click(); await p.waitForTimeout(2500);
let d = p.locator('.modal.show').last();
await d.locator('select').first().selectOption('Amina Test'); await d.locator('input[type="password"]').fill('1111'); await d.getByRole('button', { name: 'Sign in' }).click(); await p.waitForTimeout(3000);
d = p.locator('.modal.show').last();
await d.locator('input[data-fieldname="guest_name"]').fill(GUEST); await d.locator('input[data-fieldname="covers"]').fill('1'); await d.locator('input[data-fieldname="covers"]').press('Tab'); await p.waitForTimeout(3000);
const opts = await d.locator('select[data-fieldname="table"] option').allTextContents();
await d.locator('select[data-fieldname="table"]').selectOption({ label: opts.find(o => o.includes(TABLE)) || opts[1] });
await d.getByRole('button', { name: 'Seat & open order' }).click(); await p.waitForTimeout(9000);
const cards = p.locator('.order-manage .small-box.item:visible'); await cards.first().waitFor({ timeout: 45000 });
await cards.first().locator('.add-item').click({ force: true }); await p.waitForTimeout(3500);
await p.locator('.order-manage .pad-btn.btn-order').first().dblclick({ force: true }); await p.waitForTimeout(6000);
await p.locator('.order-manage').getByText(/^Complete$/).first().click({ force: true }); await p.waitForTimeout(5000);
const pay = p.locator('.modal.show').filter({ has: p.locator('.rm-mpesa-code') }).first();
const input = (label) => pay.locator('.form-group').filter({ has: p.locator(`label:text-is("${label}")`) }).locator('input').first();
const total = parseFloat(await input('Cash').inputValue());
ok('the pay form offers "+ another M-Pesa payment"', (await pay.locator('.rm-mpesa-add').count()) === 1);
await input('Cash').fill('0'); await input('Cash').dispatchEvent('change');
await input('M-Pesa').fill(String(total - 50)); await input('M-Pesa').dispatchEvent('change');
await pay.locator('.rm-mpesa-code').first().fill(C1); await pay.locator('.rm-mpesa-code').first().dispatchEvent('keyup');
await pay.locator('.rm-mpesa-add').click(); await p.waitForTimeout(800);
ok('a second amount and code row appears', (await pay.locator('.rm-mpesa-split-amount').count()) === 1 && (await pay.locator('.rm-mpesa-split-code').count()) === 1);
await pay.locator('.rm-mpesa-split-amount').fill('50'); await pay.locator('.rm-mpesa-split-amount').dispatchEvent('change'); await p.waitForTimeout(500);
const paid = await pay.locator('[data-fieldname="total_payment"] input, input[data-fieldname="total_payment"]').first().inputValue().catch(() => null);
ok('the paid total counts both transactions', paid === null || Math.abs(parseFloat(paid) - total) < 0.01, `paid ${paid} of ${total}`);
const payBtn = () => pay.getByText(/^Pay\b/).first();
await payBtn().click({ force: true }); await p.waitForTimeout(2500);
ok('paying with the second code missing is refused', (await p.locator('.desk-alert, .alert').filter({ hasText: /confirmation code/ }).count()) > 0 && (await pay.count()) === 1);
await p.waitForTimeout(7500);
await pay.locator('.rm-mpesa-split-code').fill(C2); await pay.locator('.rm-mpesa-split-code').dispatchEvent('keyup');
await payBtn().click({ force: true }); await p.waitForTimeout(12000);
const inv = await p.evaluate(async (g) => {
  const i = (await frappe.call('frappe.client.get_list', { doctype: 'POS Invoice', filters: { customer_name: g, docstatus: 1 }, fields: ['name', 'paid_amount'], limit_page_length: 1 })).message[0];
  if (!i) return null; const doc = (await frappe.call('frappe.client.get', { doctype: 'POS Invoice', name: i.name })).message;
  return { name: doc.name, paid: doc.paid_amount, rows: (doc.payments || []).filter(r => r.amount).map(r => [r.mode_of_payment, r.amount, r.reference_no]) };
}, GUEST);
ok('the invoice carries two M-Pesa rows with both codes, adding up to the bill', inv && inv.rows.length === 2 && inv.rows.every(r => /pesa/i.test(r[0])) && inv.rows.map(r => r[2]).sort().join() === [C1, C2].sort().join() && Math.abs(inv.rows.reduce((t, r) => t + r[1], 0) - total) < 0.01, JSON.stringify(inv));
ok('no page errors', errs.length === 0, errs.join(' | '));
console.log(`RESULT ${report.filter(Boolean).length}/${report.length}`);
await b.close();
process.exit(report.every(Boolean) ? 0 : 1);
