# Etham Eatery food menu, Revision 1 (23 Aug 2026), transcribed from the printed
# menu. Prices in KES. Coffee singles/doubles and juice small/big are separate
# items because a POS sells them as separate buttons.

VEG, NON_VEG = "Veg", "Non-Veg"

# (category, item name, description, price, veg/non-veg)
MENU = [
    ("Breakfast", "Full Breakfast", "Toast or pancakes, eggs, sausages, potatoes and a fruit bowl, with brewed coffee, tea or dawa", 900, NON_VEG),
    ("Breakfast", "Semi Full Breakfast", "Toast, eggs or sausages, and a fruit bowl, with brewed coffee, tea or dawa", 600, NON_VEG),

    ("Breakfast Favourites", "Bacon", "", 150, NON_VEG),
    ("Breakfast Favourites", "Boiled Eggs", "Minimum 2", 100, NON_VEG),
    ("Breakfast Favourites", "Muesli / Granola Bowl with Yoghurt", "", 300, VEG),
    ("Breakfast Favourites", "French Toast", "", 200, VEG),
    ("Breakfast Favourites", "Fried Eggs", "", 150, NON_VEG),
    ("Breakfast Favourites", "Omelette", "", 150, NON_VEG),
    ("Breakfast Favourites", "Pancakes / Crepes", "", 150, VEG),
    ("Breakfast Favourites", "Sausages", "Minimum 2", 120, NON_VEG),
    ("Breakfast Favourites", "Spanish Omelette", "", 200, NON_VEG),
    ("Breakfast Favourites", "Toast", "", 200, VEG),
    ("Breakfast Favourites", "Rolex", "", 200, NON_VEG),
    ("Breakfast Favourites", "Rolex with Spanish Omelette", "", 250, NON_VEG),

    ("Healthy & Local Favourites", "Nduma", "", 100, VEG),
    ("Healthy & Local Favourites", "Ngwaci", "", 100, VEG),
    ("Healthy & Local Favourites", "Boiled Maize", "", 100, VEG),
    ("Healthy & Local Favourites", "Plantain", "", 200, VEG),
    ("Healthy & Local Favourites", "Nduma with Beef", "", 500, NON_VEG),
    ("Healthy & Local Favourites", "Nduma with Veges", "", 200, VEG),

    ("Bakery & Light Bites", "Buns", "", 60, VEG),
    ("Bakery & Light Bites", "Muffins", "", 100, VEG),
    ("Bakery & Light Bites", "Cake Slices", "", 150, VEG),
    ("Bakery & Light Bites", "Cinnamon Roll", "", 100, VEG),
    ("Bakery & Light Bites", "Sausage Rolls", "", 150, NON_VEG),
    ("Bakery & Light Bites", "Beef Pie", "", 200, NON_VEG),
    ("Bakery & Light Bites", "Chicken Pie", "", 200, NON_VEG),
    ("Bakery & Light Bites", "Samosa Pair", "", 120, NON_VEG),
    ("Bakery & Light Bites", "Kebab", "", 150, NON_VEG),
    ("Bakery & Light Bites", "Maandazi", "", 50, VEG),

    ("Sandwiches", "Classic Chicken Sandwich", "", 500, NON_VEG),
    ("Sandwiches", "Roast Beef & Cheddar Sandwich", "", 500, NON_VEG),
    ("Sandwiches", "Club Sandwich", "", 500, NON_VEG),
    ("Sandwiches", "Egg Sandwich", "", 500, NON_VEG),
    ("Sandwiches", "Vegetable Sandwich", "", 400, VEG),

    ("Wraps", "Beef Wrap", "", 500, NON_VEG),
    ("Wraps", "Chicken Wrap", "", 500, NON_VEG),
    ("Wraps", "Veggie Wrap", "", 500, VEG),

    ("Chicken", "Roasted Chicken 1/4", "Served with rice, ugali or chapati", 400, NON_VEG),
    ("Chicken", "Roasted Chicken 1/2", "Served with rice, ugali or chapati", 750, NON_VEG),
    ("Chicken", "Roasted Chicken Full", "Served with rice, ugali or chapati", 1500, NON_VEG),
    ("Chicken", "1/4 Chicken Stir Fry", "Served with rice, ugali or chapati", 400, NON_VEG),
    ("Chicken", "1/4 Chicken Wings", "Served with rice, ugali or chapati", 300, NON_VEG),
    ("Chicken", "1/4 Grilled Chicken", "Served with rice, ugali or chapati", 400, NON_VEG),
    ("Chicken", "Kuku Kienyeji 1/4", "Served with rice, ugali or chapati", 500, NON_VEG),
    ("Chicken", "Kuku Kienyeji 1/2", "Served with rice, ugali or chapati", 1000, NON_VEG),
    ("Chicken", "Kuku Kienyeji Full", "Served with rice, ugali or chapati", 1800, NON_VEG),
    ("Chicken", "Kuku Broiler 1/4", "Served with rice, ugali or chapati", 400, NON_VEG),
    ("Chicken", "Kuku Broiler 1/2", "Served with rice, ugali or chapati", 800, NON_VEG),
    ("Chicken", "Kuku Broiler Full", "Served with rice, ugali or chapati", 1600, NON_VEG),

    ("Beef & Goat", "Beef Wet Fry", "Served with rice, ugali or chapati", 450, NON_VEG),
    ("Beef & Goat", "Beef Dry Fry", "Served with rice, ugali or chapati", 450, NON_VEG),
    ("Beef & Goat", "Beef Plain", "Served with rice, ugali or chapati", 400, NON_VEG),
    ("Beef & Goat", "Etham Special Wet Goat Fry", "Served with rice, ugali or chapati", 550, NON_VEG),
    ("Beef & Goat", "Goat Meat Plain", "Served with rice, ugali or chapati", 500, NON_VEG),
    ("Beef & Goat", "Goat Dry Fry", "Served with rice, ugali or chapati", 550, NON_VEG),
    ("Beef & Goat", "Liver", "Served with rice, ugali or chapati", 500, NON_VEG),
    ("Beef & Goat", "Matumbo", "Served with rice, ugali or chapati", 300, NON_VEG),

    ("Beef Special Cuts", "T Bone Steak", "Served with fries, ugali, rice, chapati, mashed potatoes or potato saute", 800, NON_VEG),
    ("Beef Special Cuts", "Rump Steak", "Served with fries, ugali, rice, chapati, mashed potatoes or potato saute", 800, NON_VEG),
    ("Beef Special Cuts", "Sirloin Steak", "Served with fries, ugali, rice, chapati, mashed potatoes or potato saute", 900, NON_VEG),

    ("Fresh Catch", "Coconut Tilapia", "Served with fries, ugali, rice, chapati, mashed potatoes or potato saute", 700, NON_VEG),
    ("Fresh Catch", "Tilapia", "Served with fries, ugali, rice, chapati, mashed potatoes or potato saute", 600, NON_VEG),
    ("Fresh Catch", "Fish Fingers", "", 300, NON_VEG),
    ("Fresh Catch", "Fish Fillet", "Served with fries, ugali, rice, chapati, mashed potatoes or potato saute", 600, NON_VEG),

    ("Fresh from the Farm", "Githeri with Yellow Beans", "", 250, VEG),
    ("Fresh from the Farm", "Githeri Minji", "", 300, VEG),
    ("Fresh from the Farm", "Butter Beans", "Served with ugali, rice or chapati", 300, VEG),
    ("Fresh from the Farm", "Yellow Beans", "Served with ugali, rice or chapati", 250, VEG),
    ("Fresh from the Farm", "Coconut Beans", "Served with ugali, rice or chapati", 300, VEG),
    ("Fresh from the Farm", "Minji", "Served with ugali, rice or chapati", 300, VEG),
    ("Fresh from the Farm", "Managu (Main)", "Served with ugali, rice or chapati", 200, VEG),
    ("Fresh from the Farm", "Creamed Managu", "Served with ugali, rice or chapati", 250, VEG),

    ("Burgers", "Classic Burger", "Served with chips", 450, NON_VEG),
    ("Burgers", "Double Burger", "Served with chips", 550, NON_VEG),
    ("Burgers", "Vegetable Burger", "Served with chips", 400, VEG),
    ("Burgers", "Crispy Chicken Burger", "Served with chips", 550, NON_VEG),

    ("Loaded Fries", "Loaded Fries with Classic Bacon", "", 450, NON_VEG),
    ("Loaded Fries", "Loaded Fries with BBQ Beef", "", 500, NON_VEG),
    ("Loaded Fries", "Loaded Fries with BBQ Chicken", "", 500, NON_VEG),
    ("Loaded Fries", "Loaded Fries with BBQ Combo", "", 500, NON_VEG),

    ("Sides & Accompaniments", "Bhajia", "", 250, VEG),
    ("Sides & Accompaniments", "Brown Chapati", "", 60, VEG),
    ("Sides & Accompaniments", "Chapati", "", 50, VEG),
    ("Sides & Accompaniments", "Creamed Spinach", "", 200, VEG),
    ("Sides & Accompaniments", "Fried Rice", "", 150, VEG),
    ("Sides & Accompaniments", "Fries", "", 200, VEG),
    ("Sides & Accompaniments", "Kachumbari", "", 100, VEG),
    ("Sides & Accompaniments", "Masala Fries", "", 250, VEG),
    ("Sides & Accompaniments", "Naan", "3pcs", 150, VEG),
    ("Sides & Accompaniments", "Potato Saute", "", 200, VEG),
    ("Sides & Accompaniments", "Lyonnaise Potatoes", "", 200, VEG),
    ("Sides & Accompaniments", "Potato Wedges", "", 200, VEG),
    ("Sides & Accompaniments", "Managu (Side)", "", 150, VEG),
    ("Sides & Accompaniments", "Steamed Cabbages", "", 100, VEG),
    ("Sides & Accompaniments", "Terere", "", 150, VEG),
    ("Sides & Accompaniments", "Spinach", "", 100, VEG),
    ("Sides & Accompaniments", "Vegetable Rice", "", 150, VEG),
    ("Sides & Accompaniments", "White Rice", "", 100, VEG),
    ("Sides & Accompaniments", "Mukimo", "", 150, VEG),
    ("Sides & Accompaniments", "Matoke", "", 150, VEG),
    ("Sides & Accompaniments", "Ugali", "", 100, VEG),
    ("Sides & Accompaniments", "Pilau", "", 300, NON_VEG),

    ("Sharing Platters", "Mixed Grill Family Platter for 5", "With 2 litres of soda", 3000, NON_VEG),
    ("Sharing Platters", "Full Kienyeji Chicken with 4 Accompaniments", "", 1800, NON_VEG),
    ("Sharing Platters", "Full Broiler Chicken", "", 1200, NON_VEG),
    ("Sharing Platters", "1kg Goat Fry", "", 1500, NON_VEG),

    ("Desserts", "Scoop of Ice Cream", "", 100, VEG),
    ("Desserts", "Fruit Salad with Ice Cream Topping", "", 250, VEG),
    ("Desserts", "Fruit Salad with Yoghurt Topping", "", 200, VEG),
    ("Desserts", "Chef's Dessert of the Day", "", 250, VEG),

    ("Coffee", "Espresso (Single)", "", 170, VEG),
    ("Coffee", "Espresso (Double)", "", 200, VEG),
    ("Coffee", "Cappuccino (Single)", "", 200, VEG),
    ("Coffee", "Cappuccino (Double)", "", 260, VEG),
    ("Coffee", "House Coffee Black (Single)", "", 170, VEG),
    ("Coffee", "House Coffee Black (Double)", "", 200, VEG),
    ("Coffee", "House Coffee White (Single)", "", 200, VEG),
    ("Coffee", "House Coffee White (Double)", "", 250, VEG),
    ("Coffee", "Cafe Latte (Single)", "", 240, VEG),
    ("Coffee", "Cafe Latte (Double)", "", 280, VEG),
    ("Coffee", "Latte Macchiato (Single)", "", 210, VEG),
    ("Coffee", "Latte Macchiato (Double)", "", 270, VEG),
    ("Coffee", "Mocha (Single)", "", 240, VEG),
    ("Coffee", "Mocha (Double)", "", 280, VEG),
    ("Coffee", "Mint Mocha (Single)", "", 260, VEG),
    ("Coffee", "Mint Mocha (Double)", "", 300, VEG),
    ("Coffee", "Iced Coffee Black (Single)", "", 170, VEG),
    ("Coffee", "Iced Coffee Black (Double)", "", 200, VEG),
    ("Coffee", "Iced Mocha (Single)", "", 240, VEG),
    ("Coffee", "Iced Mocha (Double)", "", 280, VEG),
    ("Coffee", "Hot Chocolate (Single)", "", 150, VEG),
    ("Coffee", "Hot Chocolate (Double)", "", 200, VEG),

    ("Tea & Infusions", "African Tea", "", 80, VEG),
    ("Tea & Infusions", "Ginger Tea", "", 100, VEG),
    ("Tea & Infusions", "Masala Tea", "", 100, VEG),
    ("Tea & Infusions", "Lemon Tea", "", 150, VEG),
    ("Tea & Infusions", "Black Tea", "", 80, VEG),
    ("Tea & Infusions", "Special Tea", "", 200, VEG),
    ("Tea & Infusions", "Dawa", "Classic, cinnamon, turmeric & mint", 200, VEG),
    ("Tea & Infusions", "Special Ketepa Tea Bags", "", 100, VEG),
    ("Tea & Infusions", "Iced Tea", "", 100, VEG),
    ("Tea & Infusions", "Honey Tot", "", 50, VEG),

    ("Fresh Juice", "Mango Juice (Small)", "", 200, VEG),
    ("Fresh Juice", "Mango Juice (Big)", "", 250, VEG),
    ("Fresh Juice", "Orange Juice (Small)", "", 200, VEG),
    ("Fresh Juice", "Orange Juice (Big)", "", 250, VEG),
    ("Fresh Juice", "Apple Ginger Juice (Small)", "", 200, VEG),
    ("Fresh Juice", "Apple Ginger Juice (Big)", "", 250, VEG),
    ("Fresh Juice", "Passion Juice (Small)", "", 200, VEG),
    ("Fresh Juice", "Passion Juice (Big)", "", 250, VEG),
    ("Fresh Juice", "Beetroot Energy (Small)", "", 200, VEG),
    ("Fresh Juice", "Beetroot Energy (Big)", "", 250, VEG),
    ("Fresh Juice", "Cocktail Juice (Small)", "", 200, VEG),
    ("Fresh Juice", "Cocktail Juice (Big)", "", 250, VEG),
    ("Fresh Juice", "Pineapple Mint (Small)", "", 200, VEG),
    ("Fresh Juice", "Pineapple Mint (Big)", "", 250, VEG),

    ("Smoothies", "Etham Booster", "Yoghurt, peanuts & fruit", 400, VEG),
    ("Smoothies", "Strawberry Smoothie", "", 400, VEG),
    ("Smoothies", "Detox Green", "Spinach, banana, ginger, cucumber, lime & mango", 400, VEG),
    ("Smoothies", "Mango Smoothie", "", 400, VEG),

    ("Soft Drinks & Water", "Soda 300ml", "", 80, VEG),
    ("Soft Drinks & Water", "Pet Soda 450ml", "", 120, VEG),
    ("Soft Drinks & Water", "Novida Pet Soda 350ml", "", 100, VEG),
    ("Soft Drinks & Water", "Dasani 500ml", "", 70, VEG),
    ("Soft Drinks & Water", "Dasani 1ltr", "", 130, VEG),
    ("Soft Drinks & Water", "Non Dasani Water 500ml", "", 60, VEG),
    ("Soft Drinks & Water", "Non Dasani Water 1ltr", "", 100, VEG),
    ("Soft Drinks & Water", "Sparkling Water 500ml", "", 80, VEG),
    ("Soft Drinks & Water", "Sparkling Water 1ltr", "", 150, VEG),
]

# Which production centre plates each category.
BAR_CATEGORIES = {"Coffee", "Tea & Infusions", "Fresh Juice", "Smoothies", "Soft Drinks & Water"}
